const Images = {
  backgroundLogo: require('../assets/images/ePowerBanner1.png'),
  mainLogo: require('../assets/images/logoGreen.png'),
  greenBack: require('../assets/icons/greenArrow.png'),
  aeye: require('../assets/icons/ActiveEye.png'),
  eye: require('../assets/icons/InactiveEye.png'),
  location: require('../assets/icons/locationDarkPurple.png'),
  locationGrey: require('../assets/icons/locationGrey.png'),
  car: require('../assets/icons/carDPurple.png'),
  carGrey: require('../assets/icons/carGrey.png'),
  ddArrow: require('../assets/icons/dropDown.png'),
  notification: require('../assets/icons/Notification1.png'),
  chat: require('../assets/icons/chat.png'),
  bCharger: require('../assets/icons/chargerDPurple.png'),
  moon: require('../assets/icons/moon.png'),
  sun: require('../assets/icons/sun.png'),
  starFull: require('../assets/icons/starFull.png'),
  starHalf: require('../assets/icons/starHalf.png'),
  starEmpty: require('../assets/icons/starEmpty.png'),
  starRounded: require('../assets/icons/StarRounded.png'),
  tickGreen: require('../assets/icons/check_green.png'),
  tickWhite: require('../assets/icons/check_white.png'),
  thunder: require('../assets/icons/charge.png'),
  activeHome: require('../assets/icons/homeActive.png'),
  inactiveHome: require('../assets/icons/homeInactive.png'),
  directionWhite: require('../assets/icons/directionWhite.png'),
  activeSearch: require('../assets/icons/searchActive.png'),
  inactiveSearch: require('../assets/icons/searchInactive.png'),

  activeHistory: require('../assets/icons/clockActive.png'),
  inactiveHistory: require('../assets/icons/clockInactive.png'),

  activeProfile: require('../assets/icons/profileActive.png'),
  inactiveProfile: require('../assets/icons/profileInactive.png'),

  logoBanner: require('../assets/images/ePowerBanner2.png'),
};
export default Images;
